[phases.setup]
nixPkgs = ["libglib2.0"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "pip uninstall -y opencv-python opencv-contrib-python || true",
  "pip install opencv-python-headless"
]