[phases.setup]
aptPkgs = ["libgl1", "libglib2.0-0t64"]

[phases.build]
cmds = ["apt-get update && apt-get install -y libgl1 libglib2.0-0t64 || true", "pip install -r requirements.txt"]

[deploy]
aptPkgs = ["libgl1", "libglib2.0-0t64"]